"use client";

import { useState } from "react";
import { ChevronDown } from "lucide-react";
import { useI18n } from "@/components/providers/I18nProvider";

interface Rate { label: string; price: string; detail?: string; }
interface Category { title: string; intro: string; rates: Rate[]; rights: string; }

export function LicensingRates() {
  const { locale } = useI18n();
  const [openIndex, setOpenIndex] = useState(0);
  const categories: Category[] = locale === "fr" ? [
    { title: "Film d’entreprise", intro: "Communication institutionnelle, films de marque et contenus corporate.", rates: [{ label: "Support physique / intranet", price: "0,70 € HT / sec" }, { label: "Internet hors réseaux sociaux", price: "1,70 € HT / sec" }, { label: "Internet + réseaux sociaux", price: "2,70 € HT / sec" }, { label: "Minimum de facturation", price: "75 € HT" }], rights: "Monde · 30 ans. Redevances SACEM/SDRM éventuelles en sus." },
    { title: "Webcast", intro: "Reportages, magazines, documentaires et séries conçus pour le web.", rates: [{ label: "Reportage corporate / sponsorisé", price: "75 € HT / min entamée" }, { label: "Reportage / magazine web", price: "40 € HT / min" }, { label: "Documentaire web", price: "60 € HT / min" }, { label: "Web-série", price: "125 € HT / min" }], rights: "Internet et réseaux sociaux · Monde · 30 ans. Achat média publicitaire exclu." },
    { title: "Télévision & documentaire", intro: "Programmes TV, magazines, reportages et documentaires.", rates: [{ label: "Magazine / reportage TV", price: "60 € HT / min", detail: "ou forfait 300 € HT par magazine" }, { label: "Documentaire", price: "80 € HT / min", detail: "ou forfait 800 € HT par documentaire" }], rights: "Tous médias et supports · Monde · 30 ans, sous réserve de couverture par la licence légale." },
    { title: "Cinéma & fiction", intro: "Longs et courts métrages, séries et téléfilms.", rates: [{ label: "Long métrage", price: "450 € HT / enregistrement / min" }, { label: "Court métrage", price: "100 € HT / enregistrement / min" }, { label: "Série TV / téléfilm", price: "250 € HT / enregistrement / min" }], rights: "Tous médias · Monde · 30 ans. Une autorisation gratuite peut être étudiée pour certains projets non commerciaux." },
    { title: "Publicité", intro: "Campagnes TV, radio, cinéma, web et diffusion en magasin.", rates: [{ label: "Télévision", price: "2 500 € HT / enregistrement", detail: "toutes chaînes · 1 an · France" }, { label: "Radio", price: "1 000 € HT / enregistrement" }, { label: "Cinéma", price: "1 000 € HT / enregistrement" }, { label: "Web & réseaux sociaux", price: "2 000 € HT / enregistrement" }, { label: "In-store", price: "dès 200 € HT", detail: "selon nombre de points de vente et de marques" }], rights: "Tarifs ajustables selon le plan média, la durée, les territoires et l’exclusivité." },
    { title: "Billboard, bande-annonce & package", intro: "Parrainage TV, promotion d’œuvres et accords récurrents.", rates: [{ label: "Billboard TV — une chaîne", price: "300 € HT / enregistrement / an" }, { label: "Billboard TV — toutes chaînes", price: "1 000 € HT / enregistrement / an" }, { label: "Bande-annonce film français", price: "600 € HT / enregistrement" }, { label: "Bande-annonce film étranger adaptée FR", price: "400 € HT / enregistrement" }, { label: "Packages programme / série / annuel", price: "Sur devis" }], rights: "Les périmètres détaillés sont confirmés dans l’autorisation de synchronisation." },
  ] : [
    { title: "Corporate film", intro: "Institutional communication, brand films and corporate content.", rates: [{ label: "Physical media / intranet", price: "€0.70 excl. VAT / sec" }, { label: "Internet excluding social media", price: "€1.70 excl. VAT / sec" }, { label: "Internet + social media", price: "€2.70 excl. VAT / sec" }, { label: "Minimum charge", price: "€75 excl. VAT" }], rights: "Worldwide · 30 years. SACEM/SDRM royalties may apply separately." },
    { title: "Webcast", intro: "Reports, magazines, documentaries and series made for the web.", rates: [{ label: "Corporate / sponsored report", price: "€75 excl. VAT / started min" }, { label: "Web report / magazine", price: "€40 excl. VAT / min" }, { label: "Web documentary", price: "€60 excl. VAT / min" }, { label: "Web series", price: "€125 excl. VAT / min" }], rights: "Internet and social media · Worldwide · 30 years. Paid media excluded." },
    { title: "Television & documentary", intro: "TV programmes, magazines, reports and documentaries.", rates: [{ label: "TV magazine / report", price: "€60 excl. VAT / min", detail: "or €300 flat fee per magazine" }, { label: "Documentary", price: "€80 excl. VAT / min", detail: "or €800 flat fee per documentary" }], rights: "All media and formats · Worldwide · 30 years, subject to statutory licence coverage." },
    { title: "Film & fiction", intro: "Feature films, shorts, series and TV films.", rates: [{ label: "Feature film", price: "€450 excl. VAT / recording / min" }, { label: "Short film", price: "€100 excl. VAT / recording / min" }, { label: "TV series / TV film", price: "€250 excl. VAT / recording / min" }], rights: "All media · Worldwide · 30 years. Free clearance may be considered for some non-commercial projects." },
    { title: "Advertising", intro: "TV, radio, cinema, web and in-store campaigns.", rates: [{ label: "Television", price: "€2,500 excl. VAT / recording", detail: "all channels · 1 year · France" }, { label: "Radio", price: "€1,000 excl. VAT / recording" }, { label: "Cinema", price: "€1,000 excl. VAT / recording" }, { label: "Web & social media", price: "€2,000 excl. VAT / recording" }, { label: "In-store", price: "from €200 excl. VAT", detail: "based on locations and brands" }], rights: "Rates may be adjusted to the media plan, term, territories and exclusivity." },
    { title: "Billboard, trailer & package", intro: "TV sponsorship, film promotion and recurring agreements.", rates: [{ label: "TV billboard — one channel", price: "€300 excl. VAT / recording / year" }, { label: "TV billboard — all channels", price: "€1,000 excl. VAT / recording / year" }, { label: "French film trailer", price: "€600 excl. VAT / recording" }, { label: "Foreign film trailer adapted to France", price: "€400 excl. VAT / recording" }, { label: "Programme / series / yearly packages", price: "On request" }], rights: "Detailed usage is confirmed in the synchronisation licence." },
  ];

  return <div className="grid gap-3">{categories.map((category, index) => {
    const open = openIndex === index;
    return <article key={category.title} className="parigo-frame border border-[var(--line)] bg-[var(--surface)]"><button type="button" onClick={() => setOpenIndex(open ? -1 : index)} aria-expanded={open} aria-controls={`licensing-panel-${index}`} className="group grid min-h-24 w-full grid-cols-[36px_minmax(0,1fr)_auto] items-center gap-3 px-4 py-5 text-left sm:grid-cols-[45px_minmax(0,1fr)_auto] sm:px-6 md:min-h-28 md:grid-cols-[72px_minmax(0,1fr)_auto] md:px-8"><span className="font-mono text-[.62rem] text-[var(--signal-strong)]">0{index + 1}</span><span className="min-w-0 break-words font-[var(--font-editorial)] text-3xl font-normal tracking-[-.04em] transition group-hover:text-[var(--color-primary-dark)] sm:text-4xl md:text-6xl">{category.title}</span><span className={`grid h-10 w-10 place-items-center border border-[var(--line)] transition sm:h-11 sm:w-11 ${open ? "rotate-180 bg-[var(--signal)] text-[#10110e]" : ""}`}><ChevronDown size={18} /></span></button>{open && <div id={`licensing-panel-${index}`} className="animate-[fade-in_.25s_ease-out_both] overflow-hidden"><div className="grid gap-8 border-t border-[var(--line)] px-5 pb-8 pt-6 md:grid-cols-12 md:px-8 md:pb-10"><p className="max-w-md text-[var(--text-muted)] md:col-span-4">{category.intro}</p><div className="min-w-0 md:col-span-7 md:col-start-6">{category.rates.map((rate) => <div key={rate.label} className="grid gap-1 border-t border-[var(--line)] py-4 sm:grid-cols-2"><span>{rate.label}</span><span className="break-words font-mono text-sm sm:text-right">{rate.price}{rate.detail && <small className="mt-1 block font-sans text-[var(--text-muted)]">{rate.detail}</small>}</span></div>)}<p className="mt-5 border-l-2 border-[var(--signal)] pl-4 text-sm leading-relaxed text-[var(--text-muted)]">{category.rights}</p></div></div></div>}</article>;
  })}</div>;
}
