"use client";

import { InstitutionalShell } from "@/components/layout/InstitutionalShell";
import { LegalDocument } from "@/components/institutional/LegalDocument";
import { useI18n } from "@/components/providers/I18nProvider";

export default function LegalPage() {
  const { locale } = useI18n();
  const sections = locale === "fr" ? [
    { title: "Éditeur du site", content: <><p><strong>PARIGO</strong>, société par actions simplifiée au capital de 10 000 euros, immatriculée au RCS de Paris sous le numéro B 477 670 244.</p><p>TVA intracommunautaire : FR62 477 670 244.</p><p>Siège social : 9 rue Rémy Dumoncel, 75014 Paris, France.</p><p>Téléphone : <a href="tel:+33149239476">+33 (0)1 49 23 94 76</a> · E-mail : <a href="mailto:info@parigomusic.com">info@parigomusic.com</a></p></> },
    { title: "Direction de la publication", content: <p>La direction de la publication est assurée par le représentant légal de PARIGO. Pour toute demande relative au site ou à son contenu : <a href="mailto:info@parigomusic.com">info@parigomusic.com</a>.</p> },
    { title: "Hébergement", content: <><p>Le site et ses fonctions serveur sont hébergés par <strong>Vercel Inc.</strong>, 440 N Barranca Avenue #4133, Covina, CA 91723, États-Unis.</p><p>Informations légales et confidentialité de l’hébergeur : <a href="https://vercel.com/legal/privacy-notice" target="_blank" rel="noopener noreferrer">vercel.com/legal/privacy-notice</a>.</p></> },
    { title: "Conception & développement", content: <p>Webmaster : <strong>YoDev</strong> · <a href="https://www.yodev.fr/" target="_blank" rel="noopener noreferrer">yodev.fr</a> · <a href="mailto:hello@yodev.fr">hello@yodev.fr</a>.</p> },
    { title: "Propriété intellectuelle", content: <><p>La structure du site, son identité visuelle, ses textes, marques, sélections éditoriales et bases de données sont protégés. Les compositions, paroles, enregistrements, pochettes, photographies, métadonnées et extraits sonores restent la propriété de PARIGO ou de leurs titulaires respectifs.</p><p>L’accès au catalogue, l’écoute d’un extrait, l’ajout à une sélection ou le téléchargement d’un fichier autorisé ne transfèrent aucun droit de reproduction, représentation, adaptation, synchronisation ou diffusion. Toute exploitation nécessite une autorisation écrite adaptée.</p></> },
    { title: "Catalogue, données & responsabilité", content: <><p>Harvest Media fournit l’infrastructure technique et les données opérationnelles du catalogue et des comptes. Cette qualité de fournisseur ne lui attribue pas la propriété des œuvres ou enregistrements, qui demeure attachée aux ayants droit concernés.</p><p>PARIGO veille à la qualité des informations publiées mais ne peut garantir une disponibilité permanente ni l’absence totale d’erreurs ou d’indisponibilités provenant de services tiers. Les tarifs et informations de licensing sont indicatifs : seuls un devis accepté et une autorisation écrite définissent les droits concédés.</p></> },
    { title: "Contact", content: <p>Pour signaler un contenu, exercer un droit ou demander une information : <a href="mailto:info@parigomusic.com">info@parigomusic.com</a> ou PARIGO, 9 rue Rémy Dumoncel, 75014 Paris.</p> },
  ] : [
    { title: "Website publisher", content: <><p><strong>PARIGO</strong>, a French simplified joint-stock company with share capital of €10,000, registered with the Paris Trade and Companies Register under number B 477 670 244.</p><p>EU VAT number: FR62 477 670 244.</p><p>Registered office: 9 rue Rémy Dumoncel, 75014 Paris, France.</p><p>Phone: <a href="tel:+33149239476">+33 (0)1 49 23 94 76</a> · Email: <a href="mailto:info@parigomusic.com">info@parigomusic.com</a></p></> },
    { title: "Publication director", content: <p>Publication is directed by PARIGO’s legal representative. Website enquiries may be sent to <a href="mailto:info@parigomusic.com">info@parigomusic.com</a>.</p> },
    { title: "Hosting", content: <><p>The website and its server functions are hosted by <strong>Vercel Inc.</strong>, 440 N Barranca Avenue #4133, Covina, CA 91723, United States.</p><p>Host legal and privacy information: <a href="https://vercel.com/legal/privacy-notice" target="_blank" rel="noopener noreferrer">vercel.com/legal/privacy-notice</a>.</p></> },
    { title: "Design & development", content: <p>Webmaster: <strong>YoDev</strong> · <a href="https://www.yodev.fr/" target="_blank" rel="noopener noreferrer">yodev.fr</a> · <a href="mailto:hello@yodev.fr">hello@yodev.fr</a>.</p> },
    { title: "Intellectual property", content: <><p>The website structure, visual identity, copy, trademarks, editorial selections and databases are protected. Compositions, lyrics, recordings, artwork, photographs, metadata and audio previews remain the property of PARIGO or their respective rights holders.</p><p>Accessing the catalogue, listening to a preview, adding a work to a selection or downloading an authorised file does not transfer any reproduction, communication, adaptation, synchronisation or exploitation right. Every use requires suitable written permission.</p></> },
    { title: "Catalogue, data & liability", content: <><p>Harvest Media supplies the technical infrastructure and operational data for the catalogue and accounts. Its role as a service provider does not give it ownership of the works or recordings, which remains with the relevant rights holders.</p><p>PARIGO seeks to keep information accurate but cannot guarantee continuous availability or an absolute absence of errors or third-party outages. Licensing rates and information are indicative: only an accepted quotation and written permission define the rights granted.</p></> },
    { title: "Contact", content: <p>To report content, exercise a right or request information: <a href="mailto:info@parigomusic.com">info@parigomusic.com</a> or PARIGO, 9 rue Rémy Dumoncel, 75014 Paris, France.</p> },
  ];
  return <InstitutionalShell title={locale === "fr" ? "Mentions légales" : "Legal notice"} intro={locale === "fr" ? "L’éditeur, l’hébergement et les règles qui encadrent ce site. Dernière mise à jour : 7 août 2026." : "The publisher, hosting provider and rules governing this website. Last updated: 7 August 2026."}><LegalDocument sections={sections} /></InstitutionalShell>;
}
