"use client";

import { InstitutionalShell } from "@/components/layout/InstitutionalShell";
import { LegalDocument } from "@/components/institutional/LegalDocument";
import { useI18n } from "@/components/providers/I18nProvider";

export default function TermsPage() {
  const { locale } = useI18n();
  const sections = locale === "fr" ? [
    { title: "Objet & acceptation", content: <p>Ces conditions encadrent l’accès au site Parigo et l’utilisation de ses outils de recherche, d’écoute, de sélection et de préparation de licences. Elles couvrent notamment le catalogue, les extraits audio, les comptes, favoris, playlists, recherches, tags, commentaires, téléchargements et cue sheets. En utilisant le service, vous acceptez les présentes conditions et la politique de confidentialité.</p> },
    { title: "Compte & espace de travail", content: <><p>Vous devez fournir des informations exactes, protéger vos identifiants et signaler toute utilisation non autorisée. Vous restez responsable des actions effectuées depuis votre compte et des personnes auxquelles vous transmettez une playlist ou une sélection.</p><p>Les données et fonctions membre reposent sur les services Harvest Media. PARIGO peut suspendre un compte en cas de fraude, d’atteinte à la sécurité, de violation de droits ou d’usage contraire aux présentes conditions.</p></> },
    { title: "Catalogue, extraits & sélections", content: <><p>Les métadonnées, extraits, waveforms, vidéos, playlists et outils de shortlist sont fournis pour rechercher des œuvres et préparer un projet. Leur consultation, leur écoute, leur ajout à une sélection ou leur partage ne constituent ni une autorisation de synchronisation ou de diffusion, ni un transfert de droits.</p><p>Il est interdit de copier, aspirer ou extraire massivement, republier, contourner une protection, constituer un jeu de données, entraîner ou alimenter un système automatisé, ou exploiter les contenus sans autorisation écrite.</p></> },
    { title: "Licences, téléchargements & cue sheets", content: <><p>Toute utilisation d’une composition ou d’un enregistrement dans une production nécessite les autorisations adaptées au média, au territoire, à la durée, aux formats, au nombre de diffusions et aux usages concernés. Seuls un devis accepté et une licence ou autorisation écrite font foi.</p><p>Un téléchargement, même autorisé depuis un compte, ou la génération d’une cue sheet n’accorde pas à lui seul de droit d’exploitation. Des droits d’auteur, droits voisins ou redevances de sociétés de gestion collective peuvent rester dus séparément.</p></> },
    { title: "Disponibilité & services tiers", content: <p>PARIGO peut faire évoluer le catalogue et les fonctionnalités, interrompre temporairement le service ou retirer un contenu. Certaines fonctions dépendent de Harvest Media, Vercel, YouTube, Resend ou d’autres prestataires : aucune lecture, donnée, vidéo ou possibilité de téléchargement ne peut être garantie de manière permanente.</p> },
    { title: "Responsabilité", content: <p>Dans les limites permises par la loi, PARIGO ne répond pas des dommages indirects, pertes de données ou décisions prises sur la base d’informations indicatives. Rien dans ces conditions n’exclut une responsabilité qui ne peut légalement l’être.</p> },
    { title: "Droit applicable", content: <p>Les présentes conditions sont régies par le droit français. Après tentative de résolution amiable, les juridictions compétentes seront déterminées selon les règles applicables ; pour les relations entre professionnels, compétence est attribuée aux tribunaux de Paris.</p> },
    { title: "Contact", content: <p>Questions sur les conditions, le catalogue ou une licence : <a href="mailto:info@parigomusic.com">info@parigomusic.com</a>.</p> },
  ] : [
    { title: "Purpose & acceptance", content: <p>These terms govern access to the Parigo website and use of its search, listening, selection and licence-preparation tools. They cover the catalogue, audio previews, accounts, favourites, playlists, searches, tags, comments, downloads and cue sheets. By using the service, you accept these terms and the privacy policy.</p> },
    { title: "Account & workspace", content: <><p>You must provide accurate information, protect your credentials and report unauthorised use. You remain responsible for actions performed through your account and for people to whom you send a playlist or selection.</p><p>Member data and features rely on Harvest Media services. PARIGO may suspend an account in case of fraud, security risk, infringement or use contrary to these terms.</p></> },
    { title: "Catalogue, previews & selections", content: <><p>Metadata, previews, waveforms, videos, playlists and shortlist tools are supplied to search for works and prepare a project. Viewing, listening, adding to a selection or sharing them is neither a synchronisation or exploitation licence nor a transfer of rights.</p><p>Copying, scraping or bulk extraction, republication, circumvention of protections, building a dataset, training or supplying an automated system, and unauthorised exploitation are prohibited.</p></> },
    { title: "Licences, downloads & cue sheets", content: <><p>Any use of a composition or recording in a production requires permissions for the relevant media, territory, term, formats, number of transmissions and uses. Only an accepted quotation and written licence or permission are binding.</p><p>An authorised account download or generated cue sheet does not itself grant exploitation rights. Copyright, neighbouring-right or collective-management royalties may remain payable separately.</p></> },
    { title: "Availability & third-party services", content: <p>PARIGO may evolve the catalogue and features, temporarily interrupt the service or remove content. Some functions depend on Harvest Media, Vercel, YouTube, Resend or other providers: playback, data, videos and downloads are not guaranteed permanently.</p> },
    { title: "Liability", content: <p>To the extent permitted by law, PARIGO is not liable for indirect damage, data loss or decisions based on indicative information. Nothing excludes liability that cannot legally be excluded.</p> },
    { title: "Governing law", content: <p>These terms are governed by French law. After an attempt at amicable resolution, jurisdiction is determined under applicable rules; business-to-business disputes fall within the jurisdiction of the Paris courts.</p> },
    { title: "Contact", content: <p>Questions about these terms, the catalogue or a licence: <a href="mailto:info@parigomusic.com">info@parigomusic.com</a>.</p> },
  ];
  return <InstitutionalShell title={locale === "fr" ? "Conditions d’utilisation" : "Terms of use"} intro={locale === "fr" ? "Écouter, sélectionner, télécharger et licencier : le cadre d’utilisation du service Parigo. Dernière mise à jour : 7 août 2026." : "Listening, selecting, downloading and licensing: the framework for using Parigo. Last updated: 7 August 2026."}><LegalDocument sections={sections} /></InstitutionalShell>;
}
