"use client";

import { InstitutionalShell } from "@/components/layout/InstitutionalShell";
import { LegalDocument } from "@/components/institutional/LegalDocument";
import { useI18n } from "@/components/providers/I18nProvider";

export default function PrivacyPage() {
  const { locale } = useI18n();
  const sections = locale === "fr" ? [
    { title: "Responsable du traitement", content: <p>PARIGO, 9 rue Rémy Dumoncel, 75014 Paris, est responsable des traitements décrits ci-dessous. Contact : <a href="mailto:info@parigomusic.com">info@parigomusic.com</a>.</p> },
    { title: "Données concernées", content: <><p>Selon vos usages, Parigo peut traiter : nom, entreprise, adresse e-mail, identifiants de compte, préférences, playlists, favoris, historique d’écoute et demandes de contact ou de licence.</p><p>Des données techniques limitées peuvent également être enregistrées pour la sécurité et le diagnostic : adresse IP, appareil, navigateur, dates et pages demandées.</p></> },
    { title: "Finalités & bases légales", content: <ul><li>Créer et sécuriser un compte, exécuter les fonctionnalités demandées : exécution du contrat.</li><li>Répondre aux demandes et préparer des licences : mesures précontractuelles et intérêt légitime.</li><li>Assurer la sécurité, prévenir les abus et améliorer le service : intérêt légitime.</li><li>Envoyer une newsletter ou activer des services optionnels : consentement, révocable à tout moment.</li><li>Respecter les obligations comptables et juridiques : obligation légale.</li></ul> },
    { title: "Cookies & traceurs", content: <><p>Un cookie de session essentiel, chiffré et inaccessible au JavaScript, maintient la connexion au compte Harvest. Les choix de langue, thème et consentement sont mémorisés localement afin de fournir le service demandé.</p><p>Les catégories optionnelles — préférences, mesure d’audience, médias et marketing — nécessitent votre accord lorsqu’elles sont utilisées. Vous pouvez modifier vos choix à tout moment via « Gérer les cookies » dans le footer.</p></> },
    { title: "Destinataires & transferts", content: <p>Harvest Media fournit l’infrastructure du catalogue et des comptes. Resend transmet les messages de contact, Sentry reçoit les erreurs techniques expurgées de données personnelles et Vercel héberge le service et mesure ses performances après consentement. Ces prestataires sont encadrés contractuellement ; tout transfert hors Espace économique européen repose sur un mécanisme conforme au RGPD.</p> },
    { title: "Durées de conservation", content: <><p>Les données de compte sont conservées jusqu’à sa suppression, sous réserve des obligations légales. Les demandes de contact et de licence sont conservées au maximum douze mois dans la messagerie puis supprimées ou anonymisées. Les erreurs et traces techniques sont conservées au maximum quatre-vingt-dix jours.</p><p>Le contenu du formulaire est envoyé à la messagerie de PARIGO via Resend et n’est pas persisté dans une base de données de l’application.</p></> },
    { title: "Vos droits", content: <><p>Vous disposez de droits d’accès, rectification, effacement, limitation, opposition, portabilité et retrait du consentement. Écrivez à <a href="mailto:info@parigomusic.com">info@parigomusic.com</a> en précisant votre demande.</p><p>Vous pouvez également saisir la <a href="https://www.cnil.fr/" target="_blank" rel="noreferrer">CNIL</a>.</p></> },
  ] : [
    { title: "Data controller", content: <p>PARIGO, 9 rue Rémy Dumoncel, 75014 Paris, France, is responsible for the processing described below. Contact: <a href="mailto:info@parigomusic.com">info@parigomusic.com</a>.</p> },
    { title: "Data we process", content: <><p>Depending on your use, Parigo may process your name, company, email, account identifiers, preferences, playlists, favourites, listening history and contact or licensing enquiries.</p><p>Limited technical data may be logged for security and diagnostics: IP address, device, browser, dates and requested pages.</p></> },
    { title: "Purposes & legal bases", content: <ul><li>Create and secure an account and provide requested features: performance of a contract.</li><li>Answer enquiries and prepare licences: pre-contractual measures and legitimate interests.</li><li>Secure and improve the service and prevent abuse: legitimate interests.</li><li>Send newsletters or enable optional services: consent, which may be withdrawn.</li><li>Meet accounting and legal duties: legal obligation.</li></ul> },
    { title: "Cookies & trackers", content: <><p>An essential encrypted session cookie, inaccessible to JavaScript, maintains the Harvest account connection. Language, theme and consent choices are stored locally to provide the requested service.</p><p>Optional preferences, analytics, media and marketing categories require consent when used. Choices can be changed from “Cookie settings” in the footer.</p></> },
    { title: "Recipients & transfers", content: <p>Harvest Media provides the catalogue and account infrastructure. Resend delivers contact messages, Sentry receives technical errors scrubbed of personal data, and Vercel hosts the service and measures performance after consent. These providers are contractually governed; transfers outside the EEA use a GDPR-compliant mechanism.</p> },
    { title: "Retention", content: <><p>Account data is retained until deletion, subject to legal duties. Contact and licensing enquiries are retained in the mailbox for no more than twelve months, then deleted or anonymised. Errors and technical traces are retained for no more than ninety days.</p><p>Form content is delivered to PARIGO’s mailbox through Resend and is not persisted in an application database.</p></> },
    { title: "Your rights", content: <><p>You have rights of access, correction, erasure, restriction, objection, portability and withdrawal of consent. Contact <a href="mailto:info@parigomusic.com">info@parigomusic.com</a>.</p><p>You may also complain to the French data authority, the <a href="https://www.cnil.fr/" target="_blank" rel="noreferrer">CNIL</a>.</p></> },
  ];
  return <InstitutionalShell eyebrow={locale === "fr" ? "Données & choix" : "Data & choices"} title={locale === "fr" ? "Confidentialité" : "Privacy"} intro={locale === "fr" ? "Ce que Parigo collecte, pourquoi, pendant combien de temps et les choix qui restent entre vos mains." : "What Parigo collects, why, for how long, and the choices that remain yours."}><LegalDocument sections={sections} /></InstitutionalShell>;
}
