"use client";

import { InstitutionalShell } from "@/components/layout/InstitutionalShell";
import { LegalDocument } from "@/components/institutional/LegalDocument";
import { useI18n } from "@/components/providers/I18nProvider";

export default function PrivacyPage() {
  const { locale } = useI18n();
  const sections = locale === "fr" ? [
    { title: "Responsable du traitement", content: <p>PARIGO, 9 rue Rémy Dumoncel, 75014 Paris, est responsable des traitements décrits ci-dessous. Contact : <a href="mailto:info@parigomusic.com">info@parigomusic.com</a>.</p> },
    { title: "Données concernées", content: <><p>Selon vos usages, PARIGO traite vos nom, prénom, entreprise, coordonnées, pays, identifiants de compte, préférences de téléchargement et choix de newsletter. Les fonctions membre gérées via Harvest Media peuvent enregistrer favoris, playlists, recherches sauvegardées, tags, commentaires, historique d’écoute, communications et téléchargements.</p><p>Les demandes de contact ou de licence peuvent contenir un message et une référence de piste. Des données techniques limitées — adresse IP, appareil, navigateur, dates, pages demandées et erreurs — peuvent être traitées pour la sécurité, le diagnostic et la mesure d’audience consentie.</p></> },
    { title: "Finalités & bases légales", content: <ul><li>Créer, authentifier et sécuriser un compte et fournir ses fonctions : exécution du contrat.</li><li>Enregistrer les sélections et activités demandées, préparer un téléchargement ou une cue sheet : exécution du service.</li><li>Répondre aux demandes et préparer, négocier ou suivre une licence : mesures précontractuelles et intérêt légitime.</li><li>Prévenir les abus, diagnostiquer les erreurs et améliorer les performances : intérêt légitime.</li><li>Envoyer une newsletter, mesurer l’audience ou charger certains médias tiers : consentement lorsqu’il est requis, révocable à tout moment.</li><li>Respecter les obligations comptables, réglementaires et de défense des droits : obligation légale et intérêt légitime.</li></ul> },
    { title: "Cookies, stockage local & médias", content: <><p>Un cookie de session essentiel, chiffré, sécurisé et inaccessible au JavaScript maintient la connexion au compte Harvest. La langue, le thème, le consentement et, hors connexion, la shortlist peuvent être mémorisés dans le navigateur. Le choix de thème est également conservé dans un cookie pendant un an.</p><p>Vercel Analytics et Speed Insights ne sont chargés qu’après accord pour la mesure d’audience. Les vidéos utilisent le domaine YouTube sans cookies et ne sont activées qu’après le choix correspondant. Vous pouvez modifier ces choix à tout moment via « Gérer les cookies » dans le footer.</p></> },
    { title: "Destinataires & transferts", content: <><p>Harvest Media, basé en Australie, fournit l’API du catalogue et des comptes et transmet les e-mails du formulaire de contact. Vercel héberge le service et, après consentement, mesure ses performances. Sentry reçoit des erreurs techniques dont les champs sensibles sont expurgés. YouTube fournit les vidéos après consentement.</p><p>Ces prestataires peuvent traiter des données hors de l’Espace économique européen. PARIGO les encadre contractuellement et s’appuie, selon le prestataire et le pays, sur une décision d’adéquation, des clauses contractuelles types ou un autre mécanisme prévu par le RGPD.</p></> },
    { title: "Durées de conservation", content: <><p>Les données de compte et d’activité Harvest sont conservées jusqu’à la suppression du compte, sous réserve des obligations légales et des délais nécessaires au traitement d’une opération en cours. Les demandes de contact et de licence sont conservées au maximum douze mois dans la messagerie puis supprimées ou anonymisées. Les erreurs et traces techniques sont conservées au maximum quatre-vingt-dix jours.</p><p>Le contenu du formulaire est transmis à la messagerie de PARIGO par Harvest et n’est pas persisté dans une base de données de l’application. Les préférences locales restent sur l’appareil jusqu’à leur suppression par l’utilisateur ou l’expiration du cookie concerné.</p></> },
    { title: "Vos droits", content: <><p>Vous disposez de droits d’accès, rectification, effacement, limitation, opposition, portabilité et retrait du consentement. Écrivez à <a href="mailto:info@parigomusic.com">info@parigomusic.com</a> en précisant votre demande.</p><p>Vous pouvez également saisir la <a href="https://www.cnil.fr/" target="_blank" rel="noreferrer">CNIL</a>.</p></> },
  ] : [
    { title: "Data controller", content: <p>PARIGO, 9 rue Rémy Dumoncel, 75014 Paris, France, is responsible for the processing described below. Contact: <a href="mailto:info@parigomusic.com">info@parigomusic.com</a>.</p> },
    { title: "Data we process", content: <><p>Depending on your use, PARIGO processes your name, company, contact details, country, account identifiers, download preferences and newsletter choice. Member features managed through Harvest Media may record favourites, playlists, saved searches, tags, comments, listening history, communications and downloads.</p><p>Contact or licensing enquiries may contain a message and track reference. Limited technical data — IP address, device, browser, dates, requested pages and errors — may be processed for security, diagnostics and consented analytics.</p></> },
    { title: "Purposes & legal bases", content: <ul><li>Create, authenticate and secure an account and provide its features: performance of a contract.</li><li>Save requested selections and activities or prepare a download or cue sheet: performance of the service.</li><li>Answer enquiries and prepare, negotiate or follow up a licence: pre-contractual measures and legitimate interests.</li><li>Prevent abuse, diagnose errors and improve performance: legitimate interests.</li><li>Send newsletters, measure audiences or load certain third-party media: consent where required, which may be withdrawn.</li><li>Meet accounting, regulatory and legal-defence duties: legal obligation and legitimate interests.</li></ul> },
    { title: "Cookies, local storage & media", content: <><p>An essential encrypted, secure session cookie, inaccessible to JavaScript, maintains the Harvest account connection. Language, theme, consent and, when signed out, the shortlist may be stored in the browser. The theme choice is also stored in a cookie for one year.</p><p>Vercel Analytics and Speed Insights load only after analytics consent. Videos use YouTube’s no-cookie domain and are enabled only after the relevant choice. Preferences can be changed from “Cookie settings” in the footer.</p></> },
    { title: "Recipients & transfers", content: <><p>Harvest Media, based in Australia, provides the catalogue and account API and delivers contact-form emails. Vercel hosts the service and, after consent, measures performance. Sentry receives technical errors scrubbed of sensitive fields. YouTube supplies videos after consent.</p><p>These providers may process data outside the EEA. PARIGO governs them contractually and relies, depending on the provider and country, on an adequacy decision, standard contractual clauses or another transfer mechanism.</p></> },
    { title: "Retention", content: <><p>Harvest account and activity data is retained until account deletion, subject to legal duties and the time needed to complete an operation in progress. Contact and licensing enquiries are retained in the mailbox for no more than twelve months, then deleted or anonymised. Errors and technical traces are retained for no more than ninety days.</p><p>Form content is delivered to PARIGO’s mailbox through Harvest and is not persisted in an application database. Local preferences remain on the device until the user removes them or the relevant cookie expires.</p></> },
    { title: "Your rights", content: <><p>You have rights of access, correction, erasure, restriction, objection, portability and withdrawal of consent. Contact <a href="mailto:info@parigomusic.com">info@parigomusic.com</a>.</p><p>You may also complain to the French data authority, the <a href="https://www.cnil.fr/" target="_blank" rel="noreferrer">CNIL</a>.</p></> },
  ];
  return <InstitutionalShell title={locale === "fr" ? "Confidentialité" : "Privacy"} intro={locale === "fr" ? "Ce que Parigo collecte, pourquoi, pendant combien de temps et les choix qui restent entre vos mains. Dernière mise à jour : 10 août 2026." : "What Parigo collects, why, for how long, and the choices that remain yours. Last updated: 10 August 2026."}><LegalDocument sections={sections} /></InstitutionalShell>;
}
